import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";

const neuropol = localfont({ src: "./fonts/neuropol.otf" });
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={neuropol.className} suppressHydrationWarning>
                {children}
            </body>
        </html>
    );
}
